# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('sound', models.URLField()),
                ('artist_photo', models.ImageField(upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pend', 'Pending Event'), ('Acpt', 'Accepted Event'), ('Decl', 'Declined Event')], default='Pend', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=10)),
                ('access', models.CharField(choices=[('BKR', 'Booker'), ('ART', 'Artist')], max_length=3)),
                ('hashpass', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('SEA', 'Seattle'), ('SFO', 'San Francisco')], max_length=45)),
                ('state', models.CharField(choices=[('WA', 'Washington'), ('CA', 'California')], max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('venue_phone', models.CharField(max_length=10)),
                ('venue_photo', models.ImageField(upload_to=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Users')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Events'),
        ),
        migrations.AddField(
            model_name='events',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Venues'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Events'),
        ),
        migrations.AddField(
            model_name='comments',
            name='message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Messages'),
        ),
        migrations.AddField(
            model_name='artists',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.Users'),
        ),
    ]
