# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='People',
        ),
        migrations.RenameModel(
            old_name='Venues',
            new_name='Venue',
        ),
    ]
