# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0006_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='user',
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 5, 27, 3, 56, 11, 541000, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 3, 56, 18, 817000, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='hashpass',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 3, 56, 28, 27000, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 3, 56, 36, 280000, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.People'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.People'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.People'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='booker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookr.People'),
        ),
    ]
